// Copyright (c) 2021 rookie-ninja
//
// Use of this source code is governed by an Apache-style
// license that can be found in the LICENSE file.

// Package rkgfmeta is a middleware of GoFrame framework for adding metadata in RPC response
package rkgfmeta

import (
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/rookie-ninja/rk-common/common"
	"github.com/rookie-ninja/rk-entry/entry"
	"github.com/rookie-ninja/rk-gf/interceptor"
	"github.com/rookie-ninja/rk-gf/interceptor/context"
	"time"
)

// Interceptor will add common headers as extension style in http response.
// The key is defined as bellow:
// 1: X-Request-Id: Request id generated by interceptor.
// 2: X-<Prefix-App: Application name.
// 3: X-<Prefix>-App-Version: Version of application.
// 4: X-<Prefix>-App-Unix-Time: Unix time of current application.
// 5: X-<Prefix>-Request-Received-Time: Time of current request received by application.
func Interceptor(opts ...Option) ghttp.HandlerFunc {
	set := newOptionSet(opts...)

	return func(ctx *ghttp.Request) {
		ctx.SetCtxVar(rkgfinter.RpcEntryNameKey, set.EntryName)

		requestId := rkcommon.GenerateRequestId()
		ctx.Response.RawWriter().Header().Set(rkgfctx.RequestIdKey, requestId)

		event := rkgfctx.GetEvent(ctx)
		event.SetRequestId(requestId)
		event.SetEventId(requestId)

		ctx.Response.RawWriter().Header().Set(set.AppNameKey, rkentry.GlobalAppCtx.GetAppInfoEntry().AppName)
		ctx.Response.RawWriter().Header().Set(set.AppVersionKey, rkentry.GlobalAppCtx.GetAppInfoEntry().Version)

		now := time.Now()
		ctx.Response.RawWriter().Header().Set(set.AppUnixTimeKey, now.Format(time.RFC3339Nano))
		ctx.Response.RawWriter().Header().Set(set.ReceivedTimeKey, now.Format(time.RFC3339Nano))

		ctx.Middleware.Next()
	}
}
